bot-token: "coolbottoken"
#server-name - The name of your minecraft server
server-name: "My Cool Minecraft Server"
# Bot-channel - Which channel should the bot alert server activity.
bot-channel : "bots"
#bot-logs - The channel where the bots will post any kind of logs.
bot-logs-channel: "bot-logs"

#mc-execute-enabled: Determines if users can use /mcserver execute <command> and run any command as console.
mcexecute-enabled: false


# The bot can automatically ping people when players leave/join and on server startup/shutdown.
# Put as 0 for it to not auto ping people
roleid: 0
# MySQL Connection Settings
# Using the JDBC Driver
mysql:
  enabled: false
  database-url: "database.website.com"
  database-port: 3306
  database-name: "McINFO"
  database-username: "root"
  database-password: "password"

#Enables use of the javafx gui to use some custom data.
javafxgui:
    enabled: false
    #The amount of time that the database should wait for before attempting to check commands from the GUI admin.
    command-check-delay: 5
    #Wether to send console messages to the GUI
    send-log-messages: true